import type {
  Accessory,
  AccessoryMovement,
  AuditEntry,
  Campaign,
  Customer,
  CustomerPurchase,
  CustomerReturn,
  ExchangeRecord,
  Expense,
  FmmState,
  Phone,
  Purchase,
  Supplier,
  SupplierPayment,
  Transaction,
  WarrantyClaim,
} from "./fmm-types";

export function generateDemoState(): FmmState {
  const now = new Date();
  const d = (daysAgo: number) => new Date(now.getTime() - daysAgo * 86400000).toISOString();

  const suppliers: Supplier[] = [
    {
      id: "sup_demo_1",
      name: "Dhaka Gadget Importers",
      supplier_type: "Phone",
      status: "Active Partner",
      contact: "01711-889900",
      notes: "Primary source for Apple & Google flagships. Office: Motijheel, Dhaka.",
      created_at: d(60),
    },
    {
      id: "sup_demo_2",
      name: "City Cellular Wholesalers",
      supplier_type: "Phone",
      status: "Active Partner",
      contact: "01811-223344",
      notes: "Samsung and official Android regional distributor. Office: Multiplan Center, Dhaka.",
      created_at: d(60),
    },
    {
      id: "sup_demo_3",
      name: "Smart Accessories Hub BD",
      supplier_type: "Accessory",
      status: "Active Partner",
      contact: "01911-445566",
      notes: "Anker, Baseus, Remax authorized wholesale partner. Stadium Market, Dhaka.",
      created_at: d(55),
    },
  ];

  const customers: Customer[] = [
    {
      id: "cus_demo_1",
      name: "Tanvir Ahmed",
      phone: "01712-345678",
      address: "Mujib Road, Faridpur Sadar",
      nid_number: "1992291827364",
      notes: "Loyal customer. Prefers Apple ecosystem.",
      created_at: d(40),
      updated_at: d(10),
    },
    {
      id: "cus_demo_2",
      name: "Mahmudul Hasan",
      phone: "01819-876543",
      address: "Goalchamot, Faridpur",
      nid_number: "1988291029384",
      notes: "Purchased iPhone 13 with accessories bundle.",
      created_at: d(25),
      updated_at: d(20),
    },
    {
      id: "cus_demo_3",
      name: "Sabbir Hossain",
      phone: "01911-223344",
      address: "Jhiltuly, Faridpur",
      nid_number: "1995281726354",
      notes: "Traded in Pixel 7 for upgrade.",
      created_at: d(15),
      updated_at: d(15),
    },
    {
      id: "cus_demo_4",
      name: "Nusrat Jahan",
      phone: "01798-554433",
      address: "Alipur, Faridpur",
      nid_number: "1997382716253",
      notes: "Bought Samsung Galaxy S23.",
      created_at: d(12),
      updated_at: d(12),
    },
    {
      id: "cus_demo_5",
      name: "Rakibul Islam",
      phone: "01622-998877",
      address: "Court Para, Faridpur",
      nid_number: "1990283746152",
      notes: "Frequent buyer of cables and fast chargers.",
      created_at: d(8),
      updated_at: d(8),
    },
  ];

  const phones: Phone[] = [
    {
      id: "ph_demo_1",
      imei: "354892110284719",
      imei_secondary: null,
      serial_number: "F2LX70PQMD",
      cycle_count: 42,
      battery_health: "99%",
      brand: "Apple",
      model: "iPhone 15 Pro",
      storage_ram: "128GB",
      condition: "Used - A",
      source_type: "Supplier Purchase",
      supplier_id: "sup_demo_1",
      customer_purchase_id: null,
      purchase_price: 112000,
      selling_price: 125000,
      sold_price: null,
      sold_date: null,
      status: "Available",
      condition_notes: "Flawless condition, Natural Titanium, original box included.",
      damage_checklist: { screen_scratch: false, body_dent: false, battery_issue: false, camera_blurry: false },
      warranty_repair_notes: "",
      warranty_days: 30,
      with_box: true,
      created_at: d(14),
      updated_at: d(14),
    },
    {
      id: "ph_demo_2",
      imei: "359182049182741",
      imei_secondary: null,
      serial_number: "DX3M9982PL",
      cycle_count: 185,
      battery_health: "91%",
      brand: "Apple",
      model: "iPhone 14",
      storage_ram: "128GB",
      condition: "Used - A",
      source_type: "Supplier Purchase",
      supplier_id: "sup_demo_1",
      customer_purchase_id: null,
      purchase_price: 66000,
      selling_price: 74000,
      sold_price: null,
      sold_date: null,
      status: "Available",
      condition_notes: "Midnight color, light micro-scratches on side rails.",
      damage_checklist: { screen_scratch: false, body_dent: false, battery_issue: false, camera_blurry: false },
      warranty_repair_notes: "",
      warranty_days: 30,
      with_box: false,
      created_at: d(18),
      updated_at: d(18),
    },
    {
      id: "ph_demo_3",
      imei: "358172938471920",
      imei_secondary: null,
      serial_number: "C39X0021KM",
      cycle_count: 240,
      battery_health: "88%",
      brand: "Apple",
      model: "iPhone 13",
      storage_ram: "128GB",
      condition: "Used - Good",
      source_type: "Supplier Purchase",
      supplier_id: "sup_demo_1",
      customer_purchase_id: null,
      purchase_price: 52000,
      selling_price: 59000,
      sold_price: 58500,
      sold_date: d(20),
      status: "Sold",
      condition_notes: "Starlight, genuine battery, excellent condition.",
      damage_checklist: { screen_scratch: false, body_dent: false, battery_issue: false, camera_blurry: false },
      warranty_repair_notes: "",
      warranty_days: 30,
      with_box: true,
      created_at: d(28),
      updated_at: d(20),
    },
    {
      id: "ph_demo_4",
      imei: "352948192837465",
      imei_secondary: "352948192837466",
      serial_number: "R5CW20AB98E",
      cycle_count: null,
      battery_health: "100%",
      brand: "Samsung",
      model: "Galaxy S24 Ultra",
      storage_ram: "256GB/12GB",
      condition: "Used - A",
      source_type: "Supplier Purchase",
      supplier_id: "sup_demo_2",
      customer_purchase_id: null,
      purchase_price: 119000,
      selling_price: 132000,
      sold_price: null,
      sold_date: null,
      status: "Available",
      condition_notes: "Titanium Gray with S-Pen, official Middle East variant.",
      damage_checklist: { screen_scratch: false, body_dent: false, battery_issue: false, camera_blurry: false },
      warranty_repair_notes: "",
      warranty_days: 30,
      with_box: true,
      created_at: d(10),
      updated_at: d(10),
    },
    {
      id: "ph_demo_5",
      imei: "357192837465192",
      imei_secondary: "357192837465193",
      serial_number: "R5CT991827A",
      cycle_count: null,
      battery_health: "94%",
      brand: "Samsung",
      model: "Galaxy S23",
      storage_ram: "128GB/8GB",
      condition: "Used - A",
      source_type: "Supplier Purchase",
      supplier_id: "sup_demo_2",
      customer_purchase_id: null,
      purchase_price: 58000,
      selling_price: 66000,
      sold_price: 65000,
      sold_date: d(12),
      status: "Sold",
      condition_notes: "Phantom Black, pristine screen.",
      damage_checklist: { screen_scratch: false, body_dent: false, battery_issue: false, camera_blurry: false },
      warranty_repair_notes: "",
      warranty_days: 30,
      with_box: true,
      created_at: d(22),
      updated_at: d(12),
    },
    {
      id: "ph_demo_6",
      imei: "356192837401928",
      imei_secondary: "356192837401929",
      serial_number: "R5CV882910B",
      cycle_count: null,
      battery_health: "96%",
      brand: "Samsung",
      model: "Galaxy A54 5G",
      storage_ram: "128GB/8GB",
      condition: "Used - Good",
      source_type: "Supplier Purchase",
      supplier_id: "sup_demo_2",
      customer_purchase_id: null,
      purchase_price: 29500,
      selling_price: 34500,
      sold_price: null,
      sold_date: null,
      status: "Available",
      condition_notes: "Awesome Lime, popular mid-ranger.",
      damage_checklist: { screen_scratch: false, body_dent: false, battery_issue: false, camera_blurry: false },
      warranty_repair_notes: "",
      warranty_days: 30,
      with_box: false,
      created_at: d(16),
      updated_at: d(16),
    },
    {
      id: "ph_demo_7",
      imei: "353819204918273",
      imei_secondary: null,
      serial_number: "38191FDCA0",
      cycle_count: 50,
      battery_health: "97%",
      brand: "Google",
      model: "Pixel 8",
      storage_ram: "128GB/8GB",
      condition: "Used - A",
      source_type: "Supplier Purchase",
      supplier_id: "sup_demo_1",
      customer_purchase_id: null,
      purchase_price: 53000,
      selling_price: 61000,
      sold_price: null,
      sold_date: null,
      status: "Available",
      condition_notes: "Hazel, pure Android, clean cameras.",
      damage_checklist: { screen_scratch: false, body_dent: false, battery_issue: false, camera_blurry: false },
      warranty_repair_notes: "",
      warranty_days: 30,
      with_box: true,
      created_at: d(7),
      updated_at: d(7),
    },
    {
      id: "ph_demo_8",
      imei: "354918273918274",
      imei_secondary: null,
      serial_number: "29181FDCA9",
      cycle_count: 190,
      battery_health: "90%",
      brand: "Google",
      model: "Pixel 7",
      storage_ram: "128GB/8GB",
      condition: "Used - B",
      source_type: "Buy from Customer",
      supplier_id: null,
      customer_purchase_id: "cp_demo_1",
      purchase_price: 33000,
      selling_price: 39000,
      sold_price: null,
      sold_date: null,
      status: "Available",
      condition_notes: "Obsidian, customer trade-in with verified NID. Camera bar has minor scuffs.",
      damage_checklist: { screen_scratch: true, body_dent: false, battery_issue: false, camera_blurry: false },
      warranty_repair_notes: "",
      warranty_days: 15,
      with_box: false,
      created_at: d(15),
      updated_at: d(15),
    },
    {
      id: "ph_demo_9",
      imei: "864918273918275",
      imei_secondary: "864918273918276",
      serial_number: null,
      cycle_count: 0,
      battery_health: "100%",
      brand: "Xiaomi",
      model: "Redmi Note 13 Pro+",
      storage_ram: "256GB/8GB",
      condition: "New",
      source_type: "Supplier Purchase",
      supplier_id: "sup_demo_2",
      customer_purchase_id: null,
      purchase_price: 32000,
      selling_price: 37000,
      sold_price: null,
      sold_date: null,
      status: "Available",
      condition_notes: "Brand new intact box, Midnight Black.",
      damage_checklist: { screen_scratch: false, body_dent: false, battery_issue: false, camera_blurry: false },
      warranty_repair_notes: "",
      warranty_days: 365,
      with_box: true,
      created_at: d(6),
      updated_at: d(6),
    },
    {
      id: "ph_demo_10",
      imei: "359481920384756",
      imei_secondary: "359481920384757",
      serial_number: "OP12984716",
      cycle_count: null,
      battery_health: "99%",
      brand: "OnePlus",
      model: "OnePlus 12",
      storage_ram: "256GB/12GB",
      condition: "Used - A",
      source_type: "Supplier Purchase",
      supplier_id: "sup_demo_1",
      customer_purchase_id: null,
      purchase_price: 68000,
      selling_price: 76000,
      sold_price: null,
      sold_date: null,
      status: "In Inspection",
      condition_notes: "Undergoing display touch and battery stress testing.",
      damage_checklist: { screen_scratch: false, body_dent: false, battery_issue: false, camera_blurry: false },
      warranty_repair_notes: "Routine diagnostic check before listing.",
      warranty_days: 30,
      with_box: true,
      created_at: d(2),
      updated_at: d(2),
    },
    {
      id: "ph_demo_11",
      imei: "863918273645192",
      imei_secondary: "863918273645193",
      serial_number: null,
      cycle_count: null,
      battery_health: "98%",
      brand: "Realme",
      model: "Realme 12 Pro 5G",
      storage_ram: "256GB/8GB",
      condition: "Used - A",
      source_type: "Supplier Purchase",
      supplier_id: "sup_demo_2",
      customer_purchase_id: null,
      purchase_price: 28000,
      selling_price: 33000,
      sold_price: null,
      sold_date: null,
      status: "Payment Pending",
      condition_notes: "Booked by customer Tanvir Ahmed with token money.",
      damage_checklist: { screen_scratch: false, body_dent: false, battery_issue: false, camera_blurry: false },
      warranty_repair_notes: "",
      warranty_days: 30,
      with_box: true,
      created_at: d(4),
      updated_at: d(1),
    },
  ];

  const accessories: Accessory[] = [
    {
      id: "acc_demo_1",
      name: "Anker 20W Nano USB-C Fast Charger",
      category: "Charger",
      brand: "Anker",
      model_sku: "A2633",
      variant: "White",
      unit: "pcs",
      purchase_price: 1100,
      selling_price: 1650,
      quantity: 18,
      min_threshold: 5,
      supplier_id: "sup_demo_3",
      notes: "Compact high speed PIQ 3.0 charger.",
      status: "Active",
      created_at: d(45),
      updated_at: d(20),
    },
    {
      id: "acc_demo_2",
      name: "Apple 20W USB-C Power Adapter (Original)",
      category: "Charger",
      brand: "Apple",
      model_sku: "MHJE3ZA/A",
      variant: "White",
      unit: "pcs",
      purchase_price: 2200,
      selling_price: 2900,
      quantity: 8,
      min_threshold: 4,
      supplier_id: "sup_demo_3",
      notes: "Authentic Apple packaging with security seal.",
      status: "Active",
      created_at: d(45),
      updated_at: d(15),
    },
    {
      id: "acc_demo_3",
      name: "Remax 10000mAh 22.5W Fast Power Bank",
      category: "Power Bank",
      brand: "Remax",
      model_sku: "RPP-520",
      variant: "Black",
      unit: "pcs",
      purchase_price: 1400,
      selling_price: 2100,
      quantity: 12,
      min_threshold: 4,
      supplier_id: "sup_demo_3",
      notes: "Supports PD 20W and Huawei SCP 22.5W.",
      status: "Active",
      created_at: d(40),
      updated_at: d(8),
    },
    {
      id: "acc_demo_4",
      name: "Baseus Cafule Type-C to Lightning Cable",
      category: "Charging Cable",
      brand: "Baseus",
      model_sku: "CATL-01",
      variant: "1 Meter / Black & Grey",
      unit: "pcs",
      purchase_price: 350,
      selling_price: 650,
      quantity: 24,
      min_threshold: 10,
      supplier_id: "sup_demo_3",
      notes: "Braided nylon, 20W PD fast charge.",
      status: "Active",
      created_at: d(45),
      updated_at: d(12),
    },
    {
      id: "acc_demo_5",
      name: "Baseus 100W Type-C to Type-C Braided Cable",
      category: "Charging Cable",
      brand: "Baseus",
      model_sku: "CATKL-B01",
      variant: "1.2 Meter / Black",
      unit: "pcs",
      purchase_price: 450,
      selling_price: 850,
      quantity: 15,
      min_threshold: 5,
      supplier_id: "sup_demo_3",
      notes: "Supports laptops, iPads, Galaxy Super Fast Charge.",
      status: "Active",
      created_at: d(40),
      updated_at: d(10),
    },
    {
      id: "acc_demo_6",
      name: "Hoco TWS Wireless Earbuds EW48",
      category: "Earbuds",
      brand: "Hoco",
      model_sku: "EW48",
      variant: "White",
      unit: "pcs",
      purchase_price: 1250,
      selling_price: 1950,
      quantity: 6,
      min_threshold: 3,
      supplier_id: "sup_demo_3",
      notes: "Bluetooth 5.3 with pop-up window animation.",
      status: "Active",
      created_at: d(35),
      updated_at: d(8),
    },
    {
      id: "acc_demo_7",
      name: "Premium 9D Curved Tempered Glass",
      category: "Screen Protector",
      brand: "Remax",
      model_sku: "TG-9D-IP",
      variant: "iPhone 15/14 series",
      unit: "pcs",
      purchase_price: 90,
      selling_price: 250,
      quantity: 45,
      min_threshold: 15,
      supplier_id: "sup_demo_3",
      notes: "Edge to edge anti-fingerprint protection.",
      status: "Active",
      created_at: d(45),
      updated_at: d(10),
    },
    {
      id: "acc_demo_8",
      name: "Matte Liquid Silicone Case",
      category: "Phone Cover",
      brand: "Baseus",
      model_sku: "MS-CASE",
      variant: "Assorted Galaxy / iPhone",
      unit: "pcs",
      purchase_price: 120,
      selling_price: 350,
      quantity: 28,
      min_threshold: 8,
      supplier_id: "sup_demo_3",
      notes: "Soft microfiber lining inside.",
      status: "Active",
      created_at: d(45),
      updated_at: d(12),
    },
  ];

  const accessory_movements: AccessoryMovement[] = [
    {
      id: "mov_demo_1",
      accessory_id: "acc_demo_1",
      type: "Purchase",
      quantity: 20,
      direction: "in",
      unit_price: 1100,
      date: d(45),
      reason: "Initial wholesale batch",
      reference_id: "pur_demo_acc_1",
      created_at: d(45),
    },
    {
      id: "mov_demo_2",
      accessory_id: "acc_demo_1",
      type: "Sale",
      quantity: 1,
      direction: "out",
      unit_price: 1650,
      date: d(20),
      reason: "Sold with iPhone 13 (Inv #FMM-202610-01)",
      reference_id: "tx_demo_1",
      created_at: d(20),
    },
    {
      id: "mov_demo_3",
      accessory_id: "acc_demo_7",
      type: "Sale",
      quantity: 1,
      direction: "out",
      unit_price: 250,
      date: d(20),
      reason: "Sold with iPhone 13 screen install",
      reference_id: "tx_demo_1",
      created_at: d(20),
    },
    {
      id: "mov_demo_4",
      accessory_id: "acc_demo_8",
      type: "Sale",
      quantity: 1,
      direction: "out",
      unit_price: 350,
      date: d(12),
      reason: "Sold with Samsung S23",
      reference_id: "tx_demo_2",
      created_at: d(12),
    },
    {
      id: "mov_demo_5",
      accessory_id: "acc_demo_3",
      type: "Sale",
      quantity: 1,
      direction: "out",
      unit_price: 2100,
      date: d(8),
      reason: "Customer retail walk-in",
      reference_id: "tx_demo_3",
      created_at: d(8),
    },
    {
      id: "mov_demo_6",
      accessory_id: "acc_demo_6",
      type: "Sale",
      quantity: 1,
      direction: "out",
      unit_price: 1950,
      date: d(8),
      reason: "Customer retail walk-in",
      reference_id: "tx_demo_3",
      created_at: d(8),
    },
  ];

  const purchases: Purchase[] = [
    {
      id: "pur_demo_ph_1",
      supplier_id: "sup_demo_1",
      date: d(30),
      type: "Phone",
      phone_ids: ["ph_demo_1", "ph_demo_2", "ph_demo_3", "ph_demo_7", "ph_demo_10"],
      items: [
        { type: "phone", id: "ph_demo_1", name: "Apple iPhone 15 Pro", quantity: 1, unit_price: 112000, total: 112000 },
        { type: "phone", id: "ph_demo_2", name: "Apple iPhone 14", quantity: 1, unit_price: 66000, total: 66000 },
        { type: "phone", id: "ph_demo_3", name: "Apple iPhone 13", quantity: 1, unit_price: 52000, total: 52000 },
        { type: "phone", id: "ph_demo_7", name: "Google Pixel 8", quantity: 1, unit_price: 53000, total: 53000 },
        { type: "phone", id: "ph_demo_10", name: "OnePlus 12", quantity: 1, unit_price: 68000, total: 68000 },
      ],
      total_amount: 351000,
      additional_cost: 2500,
      paid_amount: 320000,
      due_amount: 33500,
      payment_status: "Due",
      notes: "Direct Dhaka flight shipment. Remaining due Tk 33,500 payable next week.",
      created_at: d(30),
    },
    {
      id: "pur_demo_ph_2",
      supplier_id: "sup_demo_2",
      date: d(25),
      type: "Phone",
      phone_ids: ["ph_demo_4", "ph_demo_5", "ph_demo_6", "ph_demo_9", "ph_demo_11"],
      items: [
        { type: "phone", id: "ph_demo_4", name: "Samsung Galaxy S24 Ultra", quantity: 1, unit_price: 119000, total: 119000 },
        { type: "phone", id: "ph_demo_5", name: "Samsung Galaxy S23", quantity: 1, unit_price: 58000, total: 58000 },
        { type: "phone", id: "ph_demo_6", name: "Samsung Galaxy A54 5G", quantity: 1, unit_price: 29500, total: 29500 },
        { type: "phone", id: "ph_demo_9", name: "Xiaomi Redmi Note 13 Pro+", quantity: 1, unit_price: 32000, total: 32000 },
        { type: "phone", id: "ph_demo_11", name: "Realme 12 Pro 5G", quantity: 1, unit_price: 28000, total: 28000 },
      ],
      total_amount: 266500,
      additional_cost: 1500,
      paid_amount: 268000,
      due_amount: 0,
      payment_status: "Paid",
      notes: "Official distributor batch. Fully cleared via Bank transfer.",
      created_at: d(25),
    },
    {
      id: "pur_demo_acc_1",
      supplier_id: "sup_demo_3",
      date: d(45),
      type: "Accessory",
      items: [
        { type: "accessory", id: "acc_demo_1", name: "Anker 20W Nano Charger", quantity: 20, unit_price: 1100, total: 22000 },
        { type: "accessory", id: "acc_demo_2", name: "Apple 20W Power Adapter", quantity: 10, unit_price: 2200, total: 22000 },
        { type: "accessory", id: "acc_demo_3", name: "Remax 10000mAh Power Bank", quantity: 15, unit_price: 1400, total: 21000 },
        { type: "accessory", id: "acc_demo_4", name: "Baseus Lightning Cable", quantity: 25, unit_price: 350, total: 8750 },
        { type: "accessory", id: "acc_demo_7", name: "Premium 9D Tempered Glass", quantity: 50, unit_price: 90, total: 4500 },
      ],
      total_amount: 78250,
      additional_cost: 800,
      paid_amount: 79050,
      due_amount: 0,
      payment_status: "Paid",
      notes: "Fast delivery via SA Paribahan courier.",
      created_at: d(45),
    },
  ];

  const supplier_payments: SupplierPayment[] = [
    {
      id: "sp_demo_1",
      supplier_id: "sup_demo_1",
      amount: 320000,
      date: d(30),
      notes: "Initial advance and bulk settlement via bKash Merchant & Cash",
      purchase_id: "pur_demo_ph_1",
      created_at: d(30),
    },
    {
      id: "sp_demo_2",
      supplier_id: "sup_demo_2",
      amount: 268000,
      date: d(25),
      notes: "Full payment via City Bank corporate transfer",
      purchase_id: "pur_demo_ph_2",
      created_at: d(25),
    },
  ];

  const customer_purchases: CustomerPurchase[] = [
    {
      id: "cp_demo_1",
      customer_id: "cus_demo_3",
      customer_name: "Sabbir Hossain",
      customer_phone: "01911-223344",
      customer_address: "Jhiltuly, Faridpur",
      nid_number: "1995281726354",
      nid_front_image: null,
      nid_back_image: null,
      additional_documents: [],
      phone_photos: [],
      phone_id: "ph_demo_8",
      purchase_price: 33000,
      created_at: d(15),
    },
  ];

  const transactions: Transaction[] = [
    {
      id: "tx_demo_1",
      phone_id: "ph_demo_3",
      type: "Sale",
      customer_id: "cus_demo_2",
      customer_name: "Mahmudul Hasan",
      customer_phone: "01819-876543",
      customer_address: "Goalchamot, Faridpur",
      amount: 60400,
      paid_amount: 60400,
      due_amount: 0,
      payment_status: "Paid",
      payment_method: "bKash",
      memo_no: "INV-202610-001",
      date: d(20),
      notes: "iPhone 13 Starlight sale + Anker 20W charger + 9D Tempered Glass.",
      items: [
        { type: "phone", id: "ph_demo_3", name: "Apple iPhone 13 (128GB)", quantity: 1, unit_price: 58500, cost_price: 52000, subtotal: 58500 },
        { type: "accessory", id: "acc_demo_1", name: "Anker 20W Nano USB-C Charger", quantity: 1, unit_price: 1650, cost_price: 1100, subtotal: 1650 },
        { type: "accessory", id: "acc_demo_7", name: "Premium 9D Curved Tempered Glass", quantity: 1, unit_price: 250, cost_price: 90, subtotal: 250 },
      ],
      payment_history: [
        { id: "pe_demo_1", date: d(20), amount: 60400, payment_method: "bKash", notes: "Full amount received via bKash" },
      ],
    },
    {
      id: "tx_demo_2",
      phone_id: "ph_demo_5",
      type: "Sale",
      customer_id: "cus_demo_4",
      customer_name: "Nusrat Jahan",
      customer_phone: "01798-554433",
      customer_address: "Alipur, Faridpur",
      amount: 65350,
      paid_amount: 65350,
      due_amount: 0,
      payment_status: "Paid",
      payment_method: "Cash",
      memo_no: "INV-202610-002",
      date: d(12),
      notes: "Samsung Galaxy S23 + Matte Case. Paid cash in shop counter.",
      items: [
        { type: "phone", id: "ph_demo_5", name: "Samsung Galaxy S23 (128GB)", quantity: 1, unit_price: 65000, cost_price: 58000, subtotal: 65000 },
        { type: "accessory", id: "acc_demo_8", name: "Matte Liquid Silicone Case", quantity: 1, unit_price: 350, cost_price: 120, subtotal: 350 },
      ],
      payment_history: [
        { id: "pe_demo_2", date: d(12), amount: 65350, payment_method: "Cash", notes: "Cash counter payment" },
      ],
    },
    {
      id: "tx_demo_3",
      phone_id: "acc_multi",
      type: "Sale",
      customer_id: "cus_demo_5",
      customer_name: "Rakibul Islam",
      customer_phone: "01622-998877",
      customer_address: "Court Para, Faridpur",
      amount: 4050,
      paid_amount: 4050,
      due_amount: 0,
      payment_status: "Paid",
      payment_method: "Cash",
      memo_no: "INV-202610-003",
      date: d(8),
      notes: "Retail accessories sale: Remax Power Bank + Hoco TWS Earbuds.",
      items: [
        { type: "accessory", id: "acc_demo_3", name: "Remax 10000mAh Power Bank", quantity: 1, unit_price: 2100, cost_price: 1400, subtotal: 2100 },
        { type: "accessory", id: "acc_demo_6", name: "Hoco TWS Wireless Earbuds EW48", quantity: 1, unit_price: 1950, cost_price: 1250, subtotal: 1950 },
      ],
      payment_history: [
        { id: "pe_demo_3", date: d(8), amount: 4050, payment_method: "Cash", notes: "Counter payment" },
      ],
    },
  ];

  const expenses: Expense[] = [
    {
      id: "exp_demo_1",
      category: "Shop Rent",
      amount: 25000,
      date: d(5),
      payment_method: "Bank",
      description: "Monthly shop showroom rent for October 2026",
      created_at: d(5),
    },
    {
      id: "exp_demo_2",
      category: "Electricity",
      amount: 3850,
      date: d(7),
      payment_method: "bKash",
      description: "WZPDCL electric utility bill payment",
      created_at: d(7),
    },
    {
      id: "exp_demo_3",
      category: "Salary",
      amount: 18000,
      date: d(6),
      payment_method: "Cash",
      description: "Sales executive monthly salary (Hasibul Hasan)",
      created_at: d(6),
    },
    {
      id: "exp_demo_4",
      category: "Internet",
      amount: 1500,
      date: d(9),
      payment_method: "bKash",
      description: "High-speed fiber optical broadband connection (Faridpur Online)",
      created_at: d(9),
    },
    {
      id: "exp_demo_5",
      category: "Transport",
      amount: 1200,
      date: d(14),
      payment_method: "Cash",
      description: "Courier & parcel collection charges from Dhaka bus stand",
      created_at: d(14),
    },
    {
      id: "exp_demo_6",
      category: "Miscellaneous",
      amount: 750,
      date: d(3),
      payment_method: "Cash",
      description: "Showroom guest tea, biscuits & sanitation supplies",
      created_at: d(3),
    },
  ];

  const campaigns: Campaign[] = [
    {
      id: "cmp_demo_1",
      name: "Autumn Festival 2026",
      description: "Free 9D glass protector and 5% discount on fast chargers with any phone purchase.",
      start_date: d(15),
      end_date: d(-15),
      status: "Active",
      budget: 15000,
      notes: "Promoted on Faridpur Mobile Mart Facebook page.",
      created_at: d(15),
      updated_at: d(15),
    },
  ];

  const warranty_claims: WarrantyClaim[] = [
    {
      id: "wc_demo_1",
      customer_id: "cus_demo_2",
      customer_name: "Mahmudul Hasan",
      customer_phone: "01819-876543",
      phone_id: "ph_demo_3",
      transaction_id: "tx_demo_1",
      claim_date: d(10),
      issue_description: "Ear speaker had low volume due to dust accumulation.",
      status: "Resolved",
      repair_cost: 0,
      customer_charge: 0,
      notes: "Speaker mesh cleaned with ultrasonic tool. Sound test 100% restored.",
      created_at: d(10),
    },
  ];

  const returns: CustomerReturn[] = [];
  const exchanges: ExchangeRecord[] = [];

  const audit_log: AuditEntry[] = [
    {
      id: "aud_demo_1",
      action: "Added",
      entity_type: "supplier",
      entity_id: "sup_demo_1",
      details: "Added supplier: Dhaka Gadget Importers",
      amount: null,
      timestamp: d(60),
    },
    {
      id: "aud_demo_2",
      action: "Added",
      entity_type: "purchase",
      entity_id: "pur_demo_ph_1",
      details: "Recorded phone purchase batch from Dhaka Gadget Importers (5 phones)",
      amount: 351000,
      timestamp: d(30),
    },
    {
      id: "aud_demo_3",
      action: "Sold",
      entity_type: "transaction",
      entity_id: "tx_demo_1",
      details: "Sale to Mahmudul Hasan (iPhone 13 + Anker Charger + 9D Glass)",
      amount: 60400,
      timestamp: d(20),
    },
    {
      id: "aud_demo_4",
      action: "Sold",
      entity_type: "transaction",
      entity_id: "tx_demo_2",
      details: "Sale to Nusrat Jahan (Samsung Galaxy S23 + Matte Case)",
      amount: 65350,
      timestamp: d(12),
    },
  ];


  return {
    suppliers,
    phones,
    accessories,
    accessory_movements,
    customers,
    purchases,
    transactions,
    supplier_payments,
    customer_purchases,
    expenses,
    campaigns,
    warranty_claims,
    returns,
    exchanges,
    audit_log,
    backups: [],
    settings: {
      low_stock_threshold: 4,
      auto_backup: "daily",
      backup_location: "D:\\FMM Backups\\",
      keep_copies: 7,
    },
  };
}
